version: 2.1
jobs:
  run-tests:
    machine: 
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: "Build Test Image"
          command: |
            ls
            docker build -t geoloc-tests .
      - run:
          name: "Run Tests"
          command: |
            docker run geoloc-tests pytest tests/tests_direct.py --apikey ${GEOLOC_API_KEY}
            docker run geoloc-tests pytest tests/tests_mocked.py --apikey ${GEOLOC_API_KEY}
            docker run geoloc-tests pytest tests/tests_with_subprocess.py --apikey ${GEOLOC_API_KEY}
workflows:
  run-tests-workflow:
    jobs:
      - run-tests